#"$schema" = 'https://starship.rs/config-schema.json'
add_newline = false

format = """
$username\
:\
$directory\
($kubernetes)\
$cmd_duration\
$git_branch\
$git_state\
$git_status\
$character"""

[username]
style_user = "green"
style_root = "green"
format = "[$user]($style)"
disabled = false
show_always = true

[directory]
style = "51"
truncate_to_repo=false
truncation_length=5

[git_branch]
format = "[$branch]($style)"
style = "bright-black"

# https://starship.rs/config/#git-status
[git_status]
format = '( [\[$all_status$ahead_behind\]]($style) )' # default format with an extra leading whitespace
style = "cyan"
modified = "*"
stashed = "≡"

[git_state]
format = '\([$state( $progress_current/$progress_total)]($style)\) '
style = "bright-black"

[cmd_duration]
format = "[$duration]($style) "
style = "yellow"

[python]
format = "[$virtualenv]($style) "
style = "bright-black"

[kubernetes]
format = '[\($context\) ](bright-black)'
#format = '[\($context:$namespace\)](bright-black)'
disabled = false

[character]
success_symbol = '[\$](bold green) '
error_symbol = '[\$](bold red) '
